services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myUSER
      POSTGRES_PASSWORD: myPASSWORD
      POSTGRES_DB: expenso
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data